# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-07 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('mode', models.CharField(choices=[('S', 'Server'), ('M', 'Manual')], max_length=1)),
                ('led0', models.CharField(max_length=20)),
                ('led1', models.CharField(max_length=20)),
                ('led2', models.CharField(max_length=20)),
                ('led3', models.CharField(max_length=20)),
                ('led4', models.CharField(max_length=20)),
                ('led5', models.CharField(max_length=20)),
                ('led6', models.CharField(max_length=20)),
                ('led7', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='EventClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blinkstick.Client')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blinkstick.Event')),
            ],
        ),
    ]
