# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-07 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blinkstick', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='token',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
